nota1 = int(raw_input("Informe a primeira nota: "))
nota2 = int(raw_input("Informe a segunda nota: "))
nota3 = int(raw_input("Informe a terceira nota: "))
nota4 = int(raw_input("Informe a quarta nota: "))
print "A media das notas eh", ((nota1 + nota2 + nota3 + nota4)/4)